-- =========================================================================
--  BRIDGE MARKETS - AFFILIATE DASHBOARD DATABASE SCHEMA (EXNESS STYLE)
-- =========================================================================

-- 1. PROFILES (Partners / Affiliates)
-- Extends the Supabase auth.users table
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    partner_id TEXT UNIQUE NOT NULL, -- e.g. 'BM_10940382'
    email TEXT UNIQUE NOT NULL,
    country TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'pending_kyc', 'suspended')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: Landings table already exists from the previous step.
-- Adding it commented out so you don't recreate it if you already did it.
/*
CREATE TABLE public.landings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    html TEXT NOT NULL,
    partner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    landing_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
*/

-- 2. REFERRAL LINKS (Campaigns)
-- Stores the custom tracking links generated by the partner
CREATE TABLE public.referral_links (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    partner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    campaign_name TEXT NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. CLICKS (Traffic Analytics)
-- Logs raw visits/clicks on the referral links or landings
CREATE TABLE public.clicks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    partner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    link_id UUID REFERENCES public.referral_links(id) ON DELETE SET NULL,
    ip_address TEXT,
    device_type TEXT, -- mobile, desktop, tablet
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. LEADS (Registered Clients)
-- Clients who registered under the partner
CREATE TABLE public.leads (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    partner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    link_id UUID REFERENCES public.referral_links(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    whatsapp TEXT,
    status TEXT DEFAULT 'registered' CHECK (status IN ('registered', 'funded', 'trading')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. COMMISSIONS (Earnings)
-- Tracks the amount of money earned by the partner per lead
CREATE TABLE public.commissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    partner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    lead_id UUID REFERENCES public.leads(id) ON DELETE SET NULL,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    type TEXT CHECK (type IN ('CPA', 'RevShare', 'Bonus')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'paid', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. WITHDRAWALS (Payout Requests)
-- Tracks partner requests to cash out their earnings
CREATE TABLE public.withdrawals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    partner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL,
    payment_method TEXT NOT NULL, -- e.g. 'crypto_usdt', 'bank_transfer'
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
--  INDEXES FOR PERFORMANCE
-- ==========================================
CREATE INDEX idx_profiles_partner_id ON public.profiles(partner_id);
CREATE INDEX idx_referral_links_partner_id ON public.referral_links(partner_id);
CREATE INDEX idx_clicks_partner_id ON public.clicks(partner_id);
CREATE INDEX idx_leads_partner_id ON public.leads(partner_id);
CREATE INDEX idx_commissions_partner_id ON public.commissions(partner_id);
CREATE INDEX idx_withdrawals_partner_id ON public.withdrawals(partner_id);

-- ==========================================
--  ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;

-- Basic Data Access Policies
CREATE POLICY "Users can view their own profile" 
ON public.profiles FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Partners view their own links" 
ON public.referral_links FOR SELECT USING (partner_id = auth.uid());

CREATE POLICY "Partners view their own clicks" 
ON public.clicks FOR SELECT USING (partner_id = auth.uid());

CREATE POLICY "Partners view their own leads" 
ON public.leads FOR SELECT USING (partner_id = auth.uid());

CREATE POLICY "Partners view their own commissions" 
ON public.commissions FOR SELECT USING (partner_id = auth.uid());

CREATE POLICY "Partners view their own withdrawals" 
ON public.withdrawals FOR SELECT USING (partner_id = auth.uid());
