import { SectionMeta } from './types';

export const SECTION_CATEGORIES: Record<string, { label: string; icon: string }> = {
    'Official': { label: 'Oficial', icon: 'verified_user' },
    'Community': { label: 'Comunidad', icon: 'groups' },
    'Utility': { label: 'Utilidad', icon: 'build' },
    'Marketing': { label: 'Marketing', icon: 'campaign' }
};

export const SECTION_CATALOG: SectionMeta[] = [
    // Blueprints para PropFirm (Blueprint 2)
    { id: 'prop_hero', name: 'PropFirm: Hero', icon: 'rocket_launch', category: 'Official', description: 'Hero oficial de cuentas fondeadas', sourceTemplate: 2, defaultContent: { tag: 'OFICIAL PROPFIRM', title: 'Opera Capital Institucional sin Arriesgar tu Dinero', desc: 'Obtén hasta $200,000 USD en capital fondeado con las mejores condiciones del mercado.', ibPhrase: 'Únete a nuestra red de traders apoyados por Bridge Markets', ctaText: 'Comenzar ahora', ctaUrl: '' } },
    { id: 'prop_about', name: 'PropFirm: Definición', icon: 'info', category: 'Official', description: '¿Qué es PropTrading? Explicación fija', sourceTemplate: 2, defaultContent: { tag: 'MODELO DE NEGOCIO', title: '¿Qué es una Cuenta Fondeada?', desc: 'Un modelo innovador donde tú pones la habilidad y nosotros el capital para operar mercados globales.' } },
    { id: 'prop_matrix_forex', name: 'PropFirm: Forex Matrix', icon: 'grid_view', category: 'Official', description: 'Tabla comparativa de retos Forex', sourceTemplate: 2, defaultContent: { tag: 'RETO FOREX', title: 'Matriz de Retos Forex', desc: 'Elige el tamaño de cuenta que mejor se adapte a tu plan de trading.' } },
    { id: 'prop_matrix_synthetic', name: 'PropFirm: Synthetic Matrix', icon: 'grid_view', category: 'Official', description: 'Tabla comparativa de retos Sintéticos', sourceTemplate: 2, defaultContent: { tag: 'RETO SINTÉTICOS', title: 'Matriz de Retos Sintéticos', desc: 'Diseñada para operar volatilidad 24/7 con spreads ultra bajos.' } },
    { id: 'prop_workflow', name: 'PropFirm: Proceso', icon: 'stepper', category: 'Official', description: '4 pasos del flujo de PropTrading', sourceTemplate: 2, defaultContent: { tag: 'PASO A PASO', title: 'Tu Camino al Capital Fondeado', desc: '4 sencillos pasos desde la evaluación hasta el cobro de tus ganancias.' } },
    { id: 'prop_rules', name: 'PropFirm: Reglas Clave', icon: 'gavel', category: 'Official', description: '8 reglas operativas oficiales', sourceTemplate: 2, defaultContent: { tag: 'TRANSPARENCIA TOTAL', title: 'Reglas del Juego Claras', desc: 'Sin letras pequeñas. Todo pensado para maximizar tu consistencia.' } },
    { id: 'prop_benefits', name: 'PropFirm: Beneficios', icon: 'verified', category: 'Official', description: 'Certificación del trader y ventajas', sourceTemplate: 2, defaultContent: { tag: 'VENTAJAS EXCLUSIVAS', title: 'Por qué elegir Bridge Markets Prop', desc: 'Hasta 90% de Split de ganancias y soporte personalizado.' } },
    { id: 'prop_community', name: 'PropFirm: Comunidad', icon: 'groups', category: 'Official', description: 'Sección editable para IB', sourceTemplate: 2, defaultContent: { communityName: 'Comunidad de Traders', communityMessage: 'Únete a nuestro grupo privado donde compartimos análisis diarios y mentoría.', photoUrl: '', ctaText: 'Únete ahora', ctaUrl: '' } },
    { id: 'prop_faq', name: 'PropFirm: FAQ', icon: 'quiz', category: 'Official', description: '8 FAQs oficiales de PropTrading', sourceTemplate: 2, defaultContent: { tag: 'PREGUNTAS FRECUENTES', title: 'Resuelve tus Dudas', desc: 'Todo lo que necesitas saber antes de solicitar tu cuenta fondeada.' } },
    { id: 'prop_final_cta', name: 'PropFirm: CTA Final', icon: 'ads_click', category: 'Official', description: 'Cierre motivacional para cuenta fondeada', sourceTemplate: 2, defaultContent: { title: '¿Listo para Demostrar tu Talento?', desc: 'Comienza hoy mismo tu evaluación y escala tu capital de trading.', ctaText: 'Obtener cuenta fondeada', ctaUrl: '' } },
    { id: 'prop_registration', name: 'PropFirm: Registro', icon: 'person_add', category: 'Official', description: 'Formulario de registro integrado', sourceTemplate: 2, defaultContent: { title: 'Regístrate y Comienza', desc: 'Completa tus datos para recibir tu acceso al portal.', buttonText: 'Crear Mi Cuenta' } },
    { id: 'prop_footer', name: 'PropFirm: Pie de página', icon: 'bottom_panel_open', category: 'Official', description: 'Pie de página con atribución IB', sourceTemplate: 2, defaultContent: { copyrightText: '© Bridge Markets Global. Todos los derechos reservados.' } },

    // Blueprints para MAM/Copy (Blueprint 3)
    { id: 'mc_hero', name: 'MAM/Copy: Hero Dual', icon: 'rocket_launch', category: 'Official', description: 'Hero dual para MAM y Copy Trading', sourceTemplate: 3, defaultContent: { tag: 'INVERSIÓN INTELIGENTE', title: 'Multiplica tu Capital Copiando a los Mejores', desc: 'Accede a estrategias probadas mediante sistemas MAM o Copy Trading automático.', ibPhrase: 'Tecnología de copia en tiempo real conectada a Bridge Markets', ctaText: 'Comenzar ahora', ctaUrl: '' } },
    { id: 'mc_tabs_nav', name: 'MAM/Copy: Navegación', icon: 'tabs', category: 'Official', description: 'Selector de producto MAM/Copy', sourceTemplate: 3, defaultContent: { tab1Label: 'Sistema MAM', tab2Label: 'Copy Trading' } },
    { id: 'mc_intro', name: 'MAM/Copy: Introducción', icon: 'info', category: 'Official', description: 'Introducción a ambos productos', sourceTemplate: 3, defaultContent: { tag: 'TECNOLOGÍA DE COPIA', title: 'Dos Maneras de Automatizar tus Resultados', desc: 'Elige entre control total con Copy Trading o gestión institucional MAM.' } },
    { id: 'mc_mam_block', name: 'MAM/Copy: Bloque MAM', icon: 'account_balance', category: 'Official', description: 'Explicación técnica del sistema MAM', sourceTemplate: 3, defaultContent: { tag: 'GESTIÓN PROFESIONAL', title: 'Multi-Account Manager (MAM)', desc: 'Asignación proporcional de lotes directo a tu cuenta de trading.' } },
    { id: 'mc_copy_block', name: 'MAM/Copy: Bloque Copy', icon: 'content_copy', category: 'Official', description: 'Explicación técnica de Copy Trading', sourceTemplate: 3, defaultContent: { tag: 'COPIA EN TIEMPO REAL', title: 'Copy Trading Automático', desc: 'Conecta tu cuenta y replica las operaciones de los traders máster en milisegundos.' } },
    { id: 'mc_comparison', name: 'MAM/Copy: Comparación', icon: 'compare', category: 'Official', description: 'Tabla comparativa lado a lado', sourceTemplate: 3, defaultContent: { tag: 'COMPARATIVA', title: 'MAM vs Copy Trading', desc: 'Compara las diferencias clave para elegir la mejor opción para tu perfil.' } },
    { id: 'mc_benefits', name: 'MAM/Copy: Beneficios', icon: 'verified', category: 'Official', description: 'Beneficios de cada producto', sourceTemplate: 3, defaultContent: { tag: 'VENTAJAS', title: 'Por qué Operar con Nuestro Sistema', desc: 'Transparencia total, control del riesgo y retiros cuando quieras.' } },
    { id: 'mc_steps', name: 'MAM/Copy: Pasos Inicio', icon: 'stepper', category: 'Official', description: 'Pasos de registro para ambos productos', sourceTemplate: 3, defaultContent: { tag: 'PASO A PASO', title: 'Cómo Empezar a Copiar', desc: 'Configura tu cuenta en 3 sencillos pasos.' } },
    { id: 'mc_faq', name: 'MAM/Copy: FAQ Dual', icon: 'quiz', category: 'Official', description: 'Preguntas frecuentes para ambos productos', sourceTemplate: 3, defaultContent: { tag: 'PREGUNTAS FRECUENTES', title: 'Dudas Comunes sobre MAM y Copy', desc: 'Aprende cómo funciona el sistema antes de conectar tu cuenta.' } },
    { id: 'mc_registration', name: 'MAM/Copy: Registro', icon: 'person_add', category: 'Official', description: 'Formulario de registro integrado', sourceTemplate: 3, defaultContent: { title: 'Conéctate a la Red', desc: 'Ingresa tu correo para recibir las instrucciones de conexión.', buttonText: 'Conectar Mi Cuenta' } },
    { id: 'mc_final_cta', name: 'MAM/Copy: CTA Final', icon: 'ads_click', category: 'Official', description: 'Cierre motivacional combinado', sourceTemplate: 3, defaultContent: { title: 'Empieza a Automatizar tus Inversiones', desc: 'Sin necesidad de experiencia previa en trading manual.', ctaText: 'Empezar a copiar', ctaUrl: '' } },
    { id: 'mc_footer', name: 'MAM/Copy: Pie de página', icon: 'bottom_panel_open', category: 'Official', description: 'Pie de página con atribución IB', sourceTemplate: 3, defaultContent: { copyrightText: '© Bridge Markets Global. Todos los derechos reservados.' } },

    // Blueprints para Pro Leverage X12 (Blueprint 4)
    { id: 'lx12_hero', name: 'X12: Hero', icon: 'rocket_launch', category: 'Official', description: 'Hero para apalancamiento x12', sourceTemplate: 4, defaultContent: { tag: 'PRO LEVERAGE X12', title: 'Multiplica tu Poder de Compra x12', desc: 'Accede a la potencia de apalancamiento extremo diseñada para traders profesionales.', ibPhrase: 'Apalancamiento amplificado con ejecución de ultra baja latencia', ctaText: 'Obtener cuenta X12', ctaUrl: '' } },
    { id: 'lx12_intro', name: 'X12: Definición', icon: 'info', category: 'Official', description: '¿Qué es Pro Leverage x12?', sourceTemplate: 4, defaultContent: { tag: 'CONCEPTO X12', title: 'Máxima Potencia de Mercado', desc: 'Entiende cómo funciona el apalancamiento inteligente x12 en tus operaciones.' } },
    { id: 'lx12_pricing', name: 'X12: Precios', icon: 'payments', category: 'Official', description: 'Tabla de precios de cuentas', sourceTemplate: 4, defaultContent: { tag: 'PLANES DE CUENTA', title: 'Elige tu Tamaño de Cuenta X12', desc: 'Desde cuentas iniciales hasta niveles institucionales.' } },
    { id: 'lx12_example', name: 'X12: Ejemplo x12', icon: 'analytics', category: 'Official', description: 'Ejemplo práctico de trading x12', sourceTemplate: 4, defaultContent: { tag: 'CASO PRÁCTICO', title: 'Ejemplo de Potencial de Retorno', desc: 'Compara una operación tradicional vs. una operación con apalancamiento X12.' } },
    { id: 'lx12_rules', name: 'X12: Reglas', icon: 'gavel', category: 'Official', description: 'Reglas clave y condiciones', sourceTemplate: 4, defaultContent: { tag: 'GESTIÓN DE RIESGO', title: 'Reglas del Programa X12', desc: 'Condiciones de flotante y límites de riesgo protegidos.' } },
    { id: 'lx12_withdrawals', name: 'X12: Retiros', icon: 'account_balance_wallet', category: 'Official', description: 'Reglas de retiro y horarios', sourceTemplate: 4, defaultContent: { tag: 'RETIROS RÁPIDOS', title: 'Procesamiento de Ganancias', desc: 'Solicita tus retiros con ejecución prioritaria en menos de 24 horas.' } },
    { id: 'lx12_benefits', name: 'X12: Beneficios', icon: 'verified', category: 'Official', description: 'Ventajas y beneficios para IB', sourceTemplate: 4, defaultContent: { tag: 'VENTAJAS X12', title: '¿Por qué operar X12?', desc: 'Spreads ajustados, cero recotizaciones y apalancamiento premium.' } },
    { id: 'lx12_community', name: 'X12: Comunidad IB', icon: 'groups', category: 'Official', description: 'Sección editable de comunidad IB', sourceTemplate: 4, defaultContent: { communityName: 'Grupo Privado X12', communityMessage: 'Aprende las mejores estrategias de gestión para cuentas X12.', photoUrl: '', ctaText: 'Habla conmigo', ctaUrl: '' } },
    { id: 'lx12_faq', name: 'X12: FAQ', icon: 'quiz', category: 'Official', description: 'Preguntas frecuentes', sourceTemplate: 4, defaultContent: { tag: 'PREGUNTAS FRECUENTES', title: 'Preguntas sobre X12', desc: 'Todo lo referente al funcionamiento del apalancamiento X12.' } },
    { id: 'lx12_final_cta', name: 'X12: CTA Final', icon: 'ads_click', category: 'Official', description: 'Cierre motivacional para x12', sourceTemplate: 4, defaultContent: { title: 'Potencia tu Trading Hoy', desc: 'Solicita tu cuenta X12 y opera al siguiente nivel.', ctaText: 'Comprar mi cuenta X12', ctaUrl: '' } },

    // Blueprints para Institucional (Blueprint 5)
    { id: 'inst_hero', name: 'Inst: Hero', icon: 'rocket_launch', category: 'Official', description: 'Hero corporativo principal', sourceTemplate: 5, defaultContent: { tag: 'BRIDGE MARKETS GLOBAL', title: 'Infraestructura de Trading Institucional', desc: 'Liquidez profunda, ejecución STP/ECN y tecnología de grado bancario.', ibPhrase: 'Socio Oficial Bridge Markets - Conectando tránsitos de liquidez global', ctaText: 'Abrir cuenta', ctaUrl: '' } },
    { id: 'inst_about', name: 'Inst: Sobre Nosotros', icon: 'info', category: 'Official', description: '¿Quién es Bridge Markets?', sourceTemplate: 5, defaultContent: { tag: 'SOBRE NOSOTROS', title: 'Broker Institucional de Nueva Generación', desc: 'Construimos puentes entre los mercados globales y los traders exigentes.' } },
    { id: 'inst_why', name: 'Inst: Por qué BM', icon: 'verified', category: 'Official', description: 'Diferenciadores clave', sourceTemplate: 5, defaultContent: { tag: 'DIFERENCIADORES', title: 'Por qué Operar con Bridge Markets', desc: 'Servidores ultra veloces en Equinix LD4 y NY4 con conectividad directa.' } },
    { id: 'inst_ecosystem', name: 'Inst: Ecosistema', icon: 'hub', category: 'Official', description: 'Vista general de todos los productos', sourceTemplate: 5, defaultContent: { tag: 'ECOSISTEMA COMPLETO', title: 'Todos los Productos en un Solo Lugar', desc: 'Forex, Criptos, Índices Sintéticos, Cuentas Fondeadas y Sistemas MAM.' } },
    { id: 'inst_selector', name: 'Inst: Perfil', icon: 'person_search', category: 'Official', description: 'Selector de perfil de inversor', sourceTemplate: 5, defaultContent: { tag: 'TU PERFIL', title: 'Diseñado para Cada Tipo de Trader', desc: 'Elige la solución que se ajusta exactamente a tu estrategia.' } },
    { id: 'inst_partners', name: 'Inst: Partners IB', icon: 'handshake', category: 'Official', description: 'Beneficios del programa de partners', sourceTemplate: 5, defaultContent: { tag: 'PROGRAMA DE SOCIOS', title: 'Programa de Partners & IB', desc: 'Las comisiones más competitivas del mercado y soporte institucional dedicado.' } },
    { id: 'inst_tech', name: 'Inst: Tecnología', icon: 'memory', category: 'Official', description: 'Stack tecnológico e infraestructura', sourceTemplate: 5, defaultContent: { tag: 'TECNOLOGÍA AVALADA', title: 'Conexión de Ultra Baja Latencia', desc: 'Servidores optimizados para MT5 con enrutamiento inteligente de órdenes.' } },
    { id: 'inst_workflow', name: 'Inst: Comenzar', icon: 'stepper', category: 'Official', description: 'Pasos del flujo de bienvenida', sourceTemplate: 5, defaultContent: { tag: 'PASOS DE ONBOARDING', title: 'Cómo Abrir tu Cuenta', desc: 'Registro rápido en 3 minutos con verificación instantánea.' } },
    { id: 'inst_community', name: 'Inst: Comunidad IB', icon: 'groups', category: 'Official', description: 'Sección editable para IB', sourceTemplate: 5, defaultContent: { communityName: 'Mesa de Análisis IB', communityMessage: 'Soporte personalizado y análisis diario directamente de nuestro equipo.', photoUrl: '', ctaText: 'Habla con soporte', ctaUrl: '' } },
    { id: 'inst_faq', name: 'Inst: FAQ', icon: 'quiz', category: 'Official', description: 'Preguntas frecuentes corporativas', sourceTemplate: 5, defaultContent: { tag: 'DUDAS CORPORATIVAS', title: 'Preguntas Frecuentes Institucionales', desc: 'Respuestas a las preguntas más comunes sobre regulación y fondos.' } },
    { id: 'inst_final_cta', name: 'Inst: CTA Final', icon: 'ads_click', category: 'Official', description: 'Cierre motivacional corporativo', sourceTemplate: 5, defaultContent: { title: 'Únete a la Evolución Financiera', desc: 'Experimenta la diferencia de operar con liquidez institucional.', ctaText: 'Registrarme ahora', ctaUrl: '' } },
    { id: 'inst_footer', name: 'Inst: Pie de página', icon: 'bottom_panel_open', category: 'Official', description: 'Pie de página corporativo', sourceTemplate: 5, defaultContent: { copyrightText: '© Bridge Markets Global Limited. Todos los derechos reservados.' } },

    // Blueprints para Synthetic Universe (Blueprint 6)
    { id: 'snu_hero', name: 'SNU: Hero', icon: 'rocket_launch', category: 'Official', description: 'Hero con display degradado y emblema BM', sourceTemplate: 6, defaultContent: { tag: 'SYNTHETIC UNIVERSE', title: 'El Universo Definitivo de Índices Sintéticos', desc: 'Operatividad 24/7 en más de 600 activos exclusivos con volatilidad garantizada.', ibPhrase: 'Conexión a los 3 ecosistemas sintéticos globales', ctaText: 'Unirse al Universo', ctaUrl: '' } },
    { id: 'snu_metrics', name: 'SNU: Métricas', icon: 'analytics', category: 'Official', description: 'Tarjetas de impacto con contadores', sourceTemplate: 6, defaultContent: { metric1Val: '630+', metric1Label: 'Mercados Sintéticos', metric2Val: '24/7', metric2Label: 'Disponibilidad Continua', metric3Val: '0.0ms', metric3Label: 'Latencia Ejecución' } },
    { id: 'snu_universes_intro', name: 'SNU: Los 3 Ecosistemas', icon: 'hub', category: 'Official', description: 'Intro visual de los 3 brokers', sourceTemplate: 6, defaultContent: { tag: 'TRES ECOSISTEMAS', title: 'Acceso Unificado a 3 Gigantes Sintéticos', desc: 'Operaciones en Bridge Markets, Deriv y Weltrade desde una sola plataforma.' } },
    { id: 'snu_u1_bm', name: 'SNU: 1. Índices Propios', icon: 'grid_view', category: 'Official', description: 'Display de familias BM', sourceTemplate: 6, defaultContent: { tag: 'BRIDGE MARKETS EXCLUSIVE', title: 'Índices Sintéticos Propios BM', desc: 'Lógica algorítmica transparente con familias Volatility, Crash & Boom e Impulse.' } },
    { id: 'snu_u2_deriv', name: 'SNU: 2. Mercados Deriv', icon: 'grid_view', category: 'Official', description: 'Tabla de equivalencias Deriv', sourceTemplate: 6, defaultContent: { tag: 'EQUIVALENCIA DERIV', title: 'Compatibilidad Total con Índices Deriv', desc: 'Opera los activos conocidos como Volatility 75, 100, Boom 500 y Crash 1000.' } },
    { id: 'snu_u3_welt', name: 'SNU: 3. Mercados Weltrade', icon: 'grid_view', category: 'Official', description: 'Tabla de mercados Weltrade', sourceTemplate: 6, defaultContent: { tag: 'MERCADOS WELTRADE', title: 'Integración Sintética Weltrade', desc: 'Diversifica tu portafolio con instrumentos sintéticos alternativos.' } },
    { id: 'snu_why', name: 'SNU: Por qué BM', icon: 'verified', category: 'Official', description: '8 argumentos competitivos', sourceTemplate: 6, defaultContent: { tag: 'VENTAJAS SNU', title: 'Por qué Operar el Universo Sintético', desc: 'Cero manipulación humana, sin eventos macroeconómicos y gráficos continuos.' } },
    { id: 'snu_workflow', name: 'SNU: Cómo Empezar', icon: 'stepper', category: 'Official', description: 'Flujo de 7 pasos', sourceTemplate: 6, defaultContent: { tag: 'GUÍA DE INICIO', title: 'Cómo Comenzar en el Universo Sintético', desc: 'Desde la creación de cuenta MT5 hasta tu primera operación.' } },
    { id: 'snu_community', name: 'SNU: Comunidad IB', icon: 'groups', category: 'Official', description: 'Sección editable de comunidad', sourceTemplate: 6, defaultContent: { communityName: 'Canal Sintético VIP', communityMessage: 'Recibe señales y plantillas de análisis para índices sintéticos.', photoUrl: '', ctaText: 'Entrar al grupo', ctaUrl: '' } },
    { id: 'snu_faq', name: 'SNU: FAQ', icon: 'quiz', category: 'Official', description: 'FAQs oficiales de SNU', sourceTemplate: 6, defaultContent: { tag: 'PREGUNTAS FRECUENTES', title: 'Preguntas sobre Sintéticos', desc: 'Resuelve dudas sobre el funcionamiento de los algoritmos sintéticos.' } },
    { id: 'snu_cta', name: 'SNU: CTA Final', icon: 'ads_click', category: 'Official', description: 'Cierre motivacional SNU', sourceTemplate: 6, defaultContent: { title: 'Ingresa al Universo Sintético', desc: 'Crea tu cuenta de pruebas o real en menos de 2 minutos.', ctaText: 'Empezar ahora', ctaUrl: '' } },
    { id: 'snu_footer', name: 'SNU: Pie de página', icon: 'bottom_panel_open', category: 'Official', description: 'Pie corporativo con atribución IB', sourceTemplate: 6, defaultContent: { copyrightText: '© Synthetic Universe - Powered by Bridge Markets Global.' } },

    // Blueprints para Índices Sintéticos (Blueprint 8)
    { id: 'sp_hero', name: 'SP: Hero Oficial', icon: 'rocket_launch', category: 'Official', description: 'Hero institucional de sintéticos', sourceTemplate: 8, defaultContent: { tag: 'ÍNDICES SINTÉTICOS 24/7', title: 'Mercados Sintéticos de Alta Volatilidad', desc: 'Opera activos digitales respaldados por algoritmos criptográficamente auditados.', communityName: '', ibPhrase: 'Conexión directa MT5 con apalancamiento flexible', ctaText: 'Abrir mi cuenta', ctaUrl: '' } },
    { id: 'sp_about', name: 'SP: Definición', icon: 'info', category: 'Official', description: '¿Qué son los índices sintéticos?', sourceTemplate: 8, defaultContent: { tag: 'CONCEPTO CLAVE', title: '¿Qué son los Índices Sintéticos?', desc: 'Simulaciones de mercado puras que reproducen el comportamiento real sin sesgo fundamental.' } },
    { id: 'sp_advantages', name: 'SP: Ventajas', icon: 'check_circle', category: 'Official', description: '6 tarjetas de ventajas oficiales', sourceTemplate: 8, defaultContent: { tag: 'BENEFICIOS CLAVE', title: 'Las 6 Ventajas de Operar Sintéticos', desc: 'Operatividad 365 días al año, ejecución inmediata y bajo margen requerido.' } },
    { id: 'sp_families', name: 'SP: Familias', icon: 'category', category: 'Official', description: 'Las 4 familias de índices BM', sourceTemplate: 8, defaultContent: { tag: 'FAMILIAS DE ACTIVOS', title: 'Nuestras 4 Familias de Índices', desc: 'Volatility, Crash & Boom, Step Index y Range Break.' } },
    { id: 'sp_workflow', name: 'SP: Cómo Operar', icon: 'stepper', category: 'Official', description: '5 pasos de metodología', sourceTemplate: 8, defaultContent: { tag: 'METODOLOGÍA', title: '5 Pasos para Dominar los Sintéticos', desc: 'Aprende a analizar patrones de precios y gestionar tu riesgo.' } },
    { id: 'sp_tech_specs', name: 'SP: Especificaciones', icon: 'analytics', category: 'Official', description: 'Tabla técnica de spreads y lotajes', sourceTemplate: 8, defaultContent: { tag: 'FIP A FIP', title: 'Especificaciones Técnicas MT5', desc: 'Revisa los lotajes mínimos, horarios y spreads por activo.' } },
    { id: 'sp_activation', name: 'SP: Plataformas', icon: 'download', category: 'Official', description: '6 pasos para empezar y MT5', sourceTemplate: 8, defaultContent: { tag: 'DESCARGA Y CONEXIÓN', title: 'Conéctate desde MetaTrader 5', desc: 'Disponible en Windows, Mac, iOS y Android.' } },
    { id: 'sp_community', name: 'SP: Comunidad IB', icon: 'groups', category: 'Official', description: 'Sección editable del IB', sourceTemplate: 8, defaultContent: { communityName: 'Traders Sintéticos', communityMessage: 'Únete a nuestra comunidad de traders sintéticos.', photoUrl: '', ctaText: 'Habla con un asesor', ctaUrl: '', whatsapp: '', telegram: '', instagram: '', tiktok: '', youtube: '' } },
    { id: 'sp_faq', name: 'SP: FAQ', icon: 'quiz', category: 'Official', description: 'Preguntas oficiales del producto', sourceTemplate: 8, defaultContent: { tag: 'RESPUESTAS RÁPIDAS', title: 'Preguntas Frecuentes', desc: 'Todo lo necesario sobre cuentas sintéticas en MetaTrader 5.' } },
    { id: 'sp_final_cta', name: 'SP: CTA Final', icon: 'ads_click', category: 'Official', description: 'Cierre motivacional', sourceTemplate: 8, defaultContent: { title: 'Comienza tu Viaje en Índices Sintéticos', desc: 'Abre tu cuenta y practica en demo o empieza con dinero real.', ctaText: 'Abrir cuenta ahora', ctaUrl: '', secondaryCtaText: 'Ver gráficos en vivo', secondaryCtaUrl: 'https://charts.bridgemarkets.global' } },
    { id: 'sp_footer', name: 'SP: Footer', icon: 'bottom_panel_open', category: 'Official', description: 'Pie de página corporativo', sourceTemplate: 8, defaultContent: { ibName: '', supportContact: '', copyrightText: '© Bridge Markets Global Limited. Todos los derechos reservados.' } },

    // Blueprints para Evento VIP (Blueprint 9)
    { id: 've_header', name: 'Evento VIP: Navegación', icon: 'menu', category: 'Official', description: 'Barra de navegación translúcida oficial del evento', sourceTemplate: 9, defaultContent: { ctaText: 'Crear cuenta', ctaUrl: '' } },
    { id: 've_hero', name: 'Evento VIP: Hero', icon: 'rocket_launch', category: 'Official', description: 'Hero con piezas de ajedrez cromadas y detalles del evento', sourceTemplate: 9, defaultContent: { tag: 'Muy pronto - gran evento', title: 'La nueva era del trading comienza aquí', desc: 'Descubre la tecnología que está definiendo los mercados financieros. Un evento íntimo, diseñado para quienes marcan el ritmo del mundo.', date: '18 de Julio, 2026 - 19:00 hrs', location: 'Hotel Royal Financial Center – Bogotá, Colombia', ctaText: 'Ver reto', ctaUrl: '' } },
    { id: 've_metrics', name: 'Evento VIP: Métricas', icon: 'analytics', category: 'Official', description: 'Fila de métricas clave con fondo de cristal', sourceTemplate: 9, defaultContent: { title: 'Métricas de Impacto', desc: 'Cifras reales de nuestra red global' } },
    { id: 've_countdown', name: 'Evento VIP: Temporizador', icon: 'timer', category: 'Official', description: 'Contador regresivo con llamada a la acción', sourceTemplate: 9, defaultContent: { countdownTarget: '2026-10-22T19:00:00', ctaText: 'VER ETAPAS DEL EVENTO', ctaUrl: '' } },
    { id: 've_split_info', name: 'Evento VIP: Información Dual', icon: 'grid_view', category: 'Official', description: 'Dos columnas simétricas de información', sourceTemplate: 9, defaultContent: { titleLeft: 'SESIÓN VIP 1', subtitleLeft: 'Innovación Algorítmica', textLeft: 'Conoce los nuevos sistemas de ejecución y liquidez de Bridge Markets.', btnLeftText: 'VER MÁS INFORMACIÓN', titleRight: 'SESIÓN VIP 2', subtitleRight: 'Estrategias Fondeadas', textRight: 'Descubre cómo los traders máster gestionan portafolios institucionales.', btnRightText: 'VER MÁS INFORMACIÓN' } },
    { id: 've_video', name: 'Evento VIP: Vídeo Promocional', icon: 'video_library', category: 'Official', description: 'Card de vídeo interactivo con cintas diagonales de fondo', sourceTemplate: 9, defaultContent: { videoTitle: 'FALTAN POCOS DÍAS', videoDesc: 'Descubre todo lo que debes saber para el gran evento de Bridge Markets', videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ' } },
    { id: 've_details', name: 'Evento VIP: Detalles y Dress Code', icon: 'event', category: 'Official', description: 'Grid de 3 tarjetas de datos y banner de código de vestimenta', sourceTemplate: 9, defaultContent: { countdownTarget: '2026-10-22T19:00:00', date: 'Miércoles, 22 de octubre de 2026', time: '19:00 Horas, registro desde las 18 Horas', place: 'Hotel Bogotá Plaza - Cra 18A #100-41, Bogotá' } },
    { id: 've_registration', name: 'Evento VIP: Registro', icon: 'person_add', category: 'Official', description: 'Formulario de registro premium', sourceTemplate: 9, defaultContent: { title: 'FORMULARIO DE REGISTRO', subtitle: 'Asegura tu cupo presencial o acceso al streaming privado.', buttonText: 'Enviar formulario' } },
    { id: 've_footer', name: 'Evento VIP: Pie de Página', icon: 'bottom_panel_open', category: 'Official', description: 'Footer con logotipos y redes sociales', sourceTemplate: 9, defaultContent: { copyrightText: '© Bridge Markets Global Limited. Todos los derechos reservados.' } }
];
