import { SectionMeta } from './types';

export const SECTION_CATALOG: SectionMeta[] = [
    // ─── HEROES ──────────────────────────
    {
        id: 'hero_dark',
        name: 'Hero Oscuro Premium',
        icon: 'dark_mode',
        category: 'hero',
        description: 'Hero elegante con fondo oscuro, gradientes y CTA prominente',
        sourceTemplate: 1,
        defaultContent: {
            badge: 'Next-Gen Social Trading',
            title: 'Empower Your',
            highlight: 'Financial Future.',
            subtitle: 'Bridge Markets MAM and Copy Trading infrastructure bridges the gap between expert strategy and individual capital.',
            cta1: 'Start Trading Now',
            cta2: 'Learn More',
            stat: '+18.4%',
            statLabel: 'Monthly Yield',
        },
    },
    {
        id: 'hero_light',
        name: 'Hero Claro Corporativo',
        icon: 'light_mode',
        category: 'hero',
        description: 'Hero con fondo claro, tipografía bold premium y estilo institucional',
        sourceTemplate: 4,
        defaultContent: {
            badge: 'V3 MASTER PORTAL',
            title: 'The Edge of',
            highlight: 'Precision.',
            subtitle: 'Experience the ultimate multi-asset liquidity gateway designed for the next generation of excellence.',
            cta1: 'Explore Ecosystem',
            cta2: 'Documentation',
            stat: '0.02ms',
            statLabel: 'NETWORK SPEED',
        },
    },
    {
        id: 'hero_gradient',
        name: 'Hero Gradiente Dinámico',
        icon: 'gradient',
        category: 'hero',
        description: 'Hero con gradiente animado y diseño ultra-moderno',
        sourceTemplate: 6,
        defaultContent: {
            badge: 'PRECISION TRADING',
            title: 'Universo de',
            highlight: 'Oportunidades.',
            subtitle: 'Opera los mercados sintéticos más avanzados del mundo con spreads ultra-competitivos y ejecución instantánea.',
            cta1: 'Abrir Cuenta',
            cta2: 'Ver Plataforma',
            stat: '24/7',
            statLabel: 'MARKETS OPEN',
        },
    },

    // ─── CONTENT ─────────────────────────
    {
        id: 'bento_grid',
        name: 'Bento Grid de Servicios',
        icon: 'dashboard',
        category: 'content',
        description: 'Grid asimétrico estilo Bento con tarjetas de diferentes tamaños',
        sourceTemplate: 4,
        defaultContent: {
            sectionLabel: 'CORE SOLUTIONS',
            title: 'Unified Infrastructure',
            cards: [
                { title: 'Sintéticos Pro', desc: 'Access exclusive synthetic markets with 24/7 uptime and institutional-grade pricing.', size: 'large' },
                { title: 'Institutional Hub', desc: 'Deep liquidity and prime brokerage services for hedge funds.', size: 'medium', accent: true },
                { title: 'MAM / PAMM', desc: 'Effortless multi-account management for signal providers.', size: 'small' },
                { title: 'Prop Trading', desc: 'Scalable capital allocation for high-performance traders.', size: 'wide' },
            ],
        },
    },
    {
        id: 'feature_split',
        name: 'Características (Imagen + Texto)',
        icon: 'view_column',
        category: 'content',
        description: 'Dos columnas con imagen a un lado y texto descriptivo al otro',
        sourceTemplate: 1,
        defaultContent: {
            title: 'Granular Insights for',
            highlight: 'Total Control.',
            subtitle: 'View detailed metrics of every master before you invest. Transparency is our core architecture.',
            features: [
                { icon: 'monitoring', title: 'Live Equity Curve', desc: 'Monitor actual drawdown and recovery cycles with tick-by-tick precision.' },
                { icon: 'pie_chart', title: 'Asset Allocation', desc: 'See exactly which instruments are driving the returns.' },
            ],
        },
    },
    {
        id: 'risk_grid',
        name: 'Grid de Seguridad / Riesgo',
        icon: 'shield',
        category: 'content',
        description: 'Grid de 4 columnas con iconos de seguridad y protección',
        sourceTemplate: 1,
        defaultContent: {
            title: 'Precision Risk Safeguards',
            subtitle: 'Advanced trading protocols designed to preserve your capital while enabling growth.',
            items: [
                { icon: 'gpp_maybe', title: 'Auto-Stop Loss', desc: 'Protect your equity with account-wide drawdown limits.' },
                { icon: 'balance', title: 'Equity Guard', desc: 'Intelligent lot sizing based on your actual balance.' },
                { icon: 'bolt', title: 'Instant Exit', desc: 'One-click disconnection from all active strategies.' },
                { icon: 'radar', title: 'Portfolio Mix', desc: 'Spread risk across multiple managers effortlessly.' },
            ],
        },
    },
    {
        id: 'multi_asset',
        name: 'Grid Multi-Activos',
        icon: 'diamond',
        category: 'content',
        description: 'Grid de iconos representando activos disponibles',
        sourceTemplate: 4,
        defaultContent: {
            sectionLabel: 'CONNECTIVITY',
            title: 'One Portal.',
            highlight: 'All Markets.',
            subtitle: 'Seamlessly swap between asset classes using a single margin pool.',
            assets: [
                { icon: 'currency_bitcoin', name: 'Crypto' },
                { icon: 'monitoring', name: 'Forex' },
                { icon: 'diamond', name: 'Metals' },
                { icon: 'show_chart', name: 'Stocks' },
                { icon: 'oil_barrel', name: 'Energy' },
                { icon: 'account_balance_wallet', name: 'Indices' },
            ],
            checks: ['2000+ Tradable Instruments', 'Cross-Asset Margin Collateral', 'Deep Institutional Liquidity Tiers'],
        },
    },
    {
        id: 'workflow_steps',
        name: 'Pasos / Cómo Funciona',
        icon: 'format_list_numbered',
        category: 'content',
        description: 'Sección de pasos numerados con dual track (inversionista / manager)',
        sourceTemplate: 1,
        defaultContent: {
            tracks: [
                {
                    badge: 'Investor Stream', badgeIcon: 'trending_up',
                    title: 'Wealth', highlight: 'Amplified.',
                    steps: [
                        { num: '01', title: 'Sync Account', desc: 'Connect your MT4/MT5 wallet via our high-speed bridge in 30 seconds.' },
                        { num: '02', title: 'Select Master', desc: 'Filter masters by risk, asset class, or history.' },
                        { num: '03', title: 'Auto-Replication', desc: 'Trades are executed in your account within 5ms of the master action.' },
                    ],
                },
                {
                    badge: 'Master Stream', badgeIcon: 'leaderboard',
                    title: 'Skill', highlight: 'Monetized.',
                    steps: [
                        { num: '01', title: 'Audit Check', desc: 'Submit your performance history for verification.' },
                        { num: '02', title: 'Pure Execution', desc: 'Trade as you always have. Our engine handles scaling.' },
                        { num: '03', title: 'Weekly Payouts', desc: 'Collect performance fees directly to your wallet.' },
                    ],
                },
            ],
        },
    },
    {
        id: 'security_fees',
        name: 'Seguridad y Tarifas',
        icon: 'lock',
        category: 'content',
        description: 'Panel dual: arquitectura de seguridad + estructura de tarifas',
        sourceTemplate: 1,
        defaultContent: {
            securityTitle: 'Institutional Security Architecture',
            securityItems: [
                { icon: 'security', title: 'Account Isolation', desc: 'Your funds never leave your personal brokerage account.' },
                { icon: 'verified_user', title: 'Multi-Node Encryption', desc: 'Trade execution commands signed with 256-bit encryption.' },
            ],
            feesTitle: 'Profit Share Economy',
            feesSubtitle: 'Our interests are aligned. We only prosper when you do.',
            fees: [
                { label: 'Platform Fee', value: '$0' },
                { label: 'Performance', value: '10-30%' },
                { label: 'Management', value: '0%' },
            ],
        },
    },

    // ─── SOCIAL PROOF ────────────────────
    {
        id: 'stats_row',
        name: 'Métricas Destacadas',
        icon: 'bar_chart',
        category: 'social_proof',
        description: 'Fila de métricas KPI grandes y llamativas',
        sourceTemplate: 4,
        defaultContent: {
            stats: [
                { value: '$142B+', label: 'YEARLY VOLUME' },
                { value: '950K', label: 'ACTIVE USERS' },
                { value: '4.2M', label: 'DAILY TRADES' },
                { value: '99.9%', label: 'UPTIME' },
            ],
        },
    },
    {
        id: 'leaderboard',
        name: 'Top Traders Leaderboard',
        icon: 'emoji_events',
        category: 'social_proof',
        description: 'Tarjetas de traders destacados con métricas de rendimiento',
        sourceTemplate: 1,
        defaultContent: {
            title: 'Top Trading',
            highlight: 'Masters',
            subtitle: 'Performance metrics verified in real-time by our clearing bridge.',
            traders: [
                { name: 'Alpha Quantum', specialty: 'Forex & Indices', returnPct: '+242%', risk: '2.4%', trending: false },
                { name: 'Vantage Equities', specialty: 'Global Bluechips', returnPct: '+156%', risk: '1.1%', trending: true },
                { name: 'Steady Yields', specialty: 'Commodities', returnPct: '+88%', risk: '0.8%', trending: false },
            ],
        },
    },
    {
        id: 'testimonials',
        name: 'Testimonios',
        icon: 'chat_bubble',
        category: 'social_proof',
        description: 'Carousel horizontal de testimonios con fotos y estrellas',
        sourceTemplate: 4,
        defaultContent: {
            sectionLabel: 'SOCIAL PROOF',
            title: 'Voices of the Portal',
            items: [
                { quote: 'The synthetic markets are unlike anything I\'ve seen. The spread is consistently tight.', name: 'Marco Rossi', role: 'Independent Quant' },
                { quote: 'Managing institutional assets requires extreme precision. Bridge provides the backbone.', name: 'Elena Vance', role: 'Fund Manager' },
                { quote: 'Integration with their API was seamless. Reduced slippage by 40% after migration.', name: 'David Chen', role: 'CTO, Alpha' },
            ],
        },
    },
    {
        id: 'trust_badges',
        name: 'Sellos de Confianza',
        icon: 'verified',
        category: 'social_proof',
        description: 'Grid de iconos de regulación y certificaciones de seguridad',
        sourceTemplate: 4,
        defaultContent: {
            sectionLabel: 'TRUST & SAFETY',
            title: 'Regulated & Encrypted',
            badges: [
                { icon: 'verified_user', label: 'ASIC Regulated' },
                { icon: 'security', label: 'FCA Compliant' },
                { icon: 'lock', label: 'AES-256 SECURE' },
                { icon: 'shield_with_heart', label: 'SIPC Insured' },
                { icon: 'gpp_maybe', label: 'Segregated' },
                { icon: 'fingerprint', label: 'Bio-Metric' },
            ],
        },
    },

    // ─── CTA ─────────────────────────────
    {
        id: 'cta_community',
        name: 'CTA Comunidad',
        icon: 'rocket_launch',
        category: 'cta',
        description: 'Franja de color con estadísticas de comunidad y botón de acción',
        sourceTemplate: 4,
        defaultContent: {
            title: 'Join the Global',
            highlight: 'Trading Community',
            subtitle: 'Connect with 1M+ active traders across our platforms.',
            communityStats: [
                { value: '250k+', label: 'Discord' },
                { value: '1.2M', label: 'Twitter' },
            ],
            cta: 'Join Discord',
        },
    },
    {
        id: 'calculator',
        name: 'Calculadora de Rendimiento',
        icon: 'calculate',
        category: 'cta',
        description: 'Calculadora interactiva de proyección de ganancias',
        sourceTemplate: 1,
        defaultContent: {
            title: 'Projected Growth',
            fields: [
                { label: 'Investment Capital', value: '$25,000' },
                { label: 'Target Monthly ROI', value: '12%' },
                { label: 'Master Fee Share', value: '20%' },
            ],
            resultLabel: 'Estimated Monthly Net Profit',
            resultValue: '$2,400',
        },
    },

    // ─── SECCIONES OFICIALES (BOCETOS DEFINITIVOS) ───────
    {
        id: 'hero_official',
        name: 'Hero Oficial Dinámico',
        icon: 'stars',
        category: 'hero',
        description: 'Hero con título corporativo fijo y subtítulo editable para el IB',
        sourceTemplate: 0,
        defaultContent: {
            fixedTitle: 'DESCUBRE EL PODER DE LOS',
            highlight: 'ÍNDICES SINTÉTICOS',
            editableSubtitle: 'Operando el futuro del trading con Bridge Markets',
            ctaText: 'ABRIR CUENTA AHORA',
        },
    },
    {
        id: 'synthetic_families',
        name: 'Familias de Índices (Grid)',
        icon: 'account_tree',
        category: 'content',
        description: 'Grid con las 4 familias oficiales: Fortune, Vortex, Bull/Bear y Fomo',
        sourceTemplate: 0,
        defaultContent: {
            title: 'Nuestras Familias de Índices',
            subtitle: 'Instrumentos exclusivos diseñados para máxima liquidez y ejecución instantánea.',
            families: [
                { name: 'FORTUNE 10-50-100', desc: 'Basados en algoritmos de volatilidad constante para scalping de precisión.' },
                { name: 'VORTEX 10-50-100', desc: 'Diseñados para capturar movimientos explosivos de tendencia.' },
                { name: 'BULL X / BEAR X', desc: 'Índices que simulan mercados alcistas y bajistas permanentes.' },
                { name: 'FOMO X / FOMO LITE', desc: 'Alta volatilidad para traders que buscan movimientos rápidos.' },
            ],
        },
    },
    {
        id: 'challenge_matrix',
        name: 'Matriz de Retos PropFirm',
        icon: 'grid_view',
        category: 'content',
        description: 'Tabla comparativa de retos (Obsidian, Basalt, Elite, Ultra)',
        sourceTemplate: 0,
        defaultContent: {
            title: 'Elige tu Reto de Fondeo',
            plans: [
                { name: 'OBSIDIAN', cap: '$10,000', fee: '$99', daily: '5%', total: '10%' },
                { name: 'BASALT', cap: '$25,000', fee: '$199', daily: '5%', total: '10%' },
                { name: 'ELITE', cap: '$50,000', fee: '$349', daily: '5%', total: '10%' },
                { name: 'ULTRA', cap: '$100,000', fee: '$599', daily: '5%', total: '10%' },
            ],
        },
    },
    {
        id: 'dual_steps',
        name: 'Pasos Duales (MAM/Copy)',
        icon: 'reorder',
        category: 'layout',
        description: 'Pasos de registro para MAM y Copy Trading en paralelo',
        sourceTemplate: 0,
        defaultContent: {
            titleMAM: 'Cómo ser un Gestor MAM',
            titleCopy: 'Cómo empezar en Copy Trading',
            stepsMAM: ['Crea tu cuenta leverage', 'Conecta tu cuenta master', 'Define tu esquema de comisiones'],
            stepsCopy: ['Selecciona un Master del ranking', 'Asigna tu capital de copia', 'Monitorea tus rendimientos'],
        },
    },
    {
        id: 'leverage_specs',
        name: 'Especificaciones X12',
        icon: 'analytics',
        category: 'content',
        description: 'Tabla técnica de apalancamiento x12 sin evaluación',
        sourceTemplate: 0,
        defaultContent: {
            title: 'Cuentas PRO Leverage x12',
            specs: [
                { label: 'Apalancamiento', value: '1:12' },
                { label: 'Evaluación', value: 'NO (Directo a Real)' },
                { label: 'Límites de Tiempo', value: 'Sin Límite' },
                { label: 'Drawdown Máximo', value: '10% Equity' },
            ],
        },
    },
    {
        id: 'universe_logic',
        name: 'Lógica del Universo (Diagrama)',
        icon: 'hub',
        category: 'layout',
        description: 'Muestra la conexión Deriv + Weltrade + Bridge Markets',
        sourceTemplate: 0,
        defaultContent: {
            title: 'El ecosistema perfecto',
            steps: [
                { name: 'DERIV', desc: 'Proveedor oficial de índices sintéticos.' },
                { name: 'WELTRADE', desc: 'Liquidez y bridge tecnológico.' },
                { name: 'BRIDGE MARKETS', desc: 'Tu portal de acceso y soporte oficial.' },
            ],
        },
    },
    // ─── BLUEPRINT 1: SINTÉTICOS ──────────────────────────
    {
        id: 'snt_hero',
        name: 'Sintéticos: Hero',
        icon: 'rocket_launch',
        category: 'hero',
        description: 'Hero oficial con título fijo y campos de afiliado editables',
        sourceTemplate: 1,
        defaultContent: {
            ibName: 'Comunidad Elite FX',
            ibPhrase: 'Opera sin pausas y lleva tu trading al siguiente nivel.',
            ctaText: 'Abrir mi cuenta'
        },
    },
    {
        id: 'snt_about',
        name: 'Sintéticos: Definición',
        icon: 'info',
        category: 'content',
        description: 'Explicación técnica de RNG y algoritmos (Contenido Fijo)',
        sourceTemplate: 1,
        defaultContent: {},
    },
    {
        id: 'snt_advantages',
        name: 'Sintéticos: Ventajas',
        icon: 'award_star',
        category: 'content',
        description: '6 tarjetas de ventajas oficiales (Contenido Fijo)',
        sourceTemplate: 1,
        defaultContent: {},
    },
    {
        id: 'snt_families',
        name: 'Sintéticos: Familias',
        icon: 'account_tree',
        category: 'content',
        description: '4 familias detalladas + Tabla (Contenido Fijo)',
        sourceTemplate: 1,
        defaultContent: {},
    },
    {
        id: 'snt_workflow',
        name: 'Sintéticos: Proceso',
        icon: 'alt_route',
        category: 'content',
        description: '5 pasos del proceso de trading (Contenido Fijo)',
        sourceTemplate: 1,
        defaultContent: {},
    },
    {
        id: 'snt_specs',
        name: 'Sintéticos: Specs',
        icon: 'list_alt',
        category: 'content',
        description: 'Tabla técnica de mercado (Contenido Fijo)',
        sourceTemplate: 1,
        defaultContent: {},
    },
    {
        id: 'snt_platforms',
        name: 'Sintéticos: Empezar',
        icon: 'download',
        category: 'content',
        description: 'Pasos de activación MT5 (Contenido Fijo)',
        sourceTemplate: 1,
        defaultContent: {},
    },
    {
        id: 'snt_community',
        name: 'Sintéticos: Comunidad',
        icon: 'groups',
        category: 'content',
        description: 'Sección exclusiva del IB completamente editable',
        sourceTemplate: 1,
        defaultContent: {
            communityName: 'Equipo de Trading VIP',
            welcomeMessage: 'Somos tu principal aliado estratégico en los mercados sintéticos. Únete y accede a herramientas únicas.',
            language: 'Español',
            btnText: 'Únete a mi comunidad',
            socialWhatsApp: '',
            socialTelegram: '',
            socialInstagram: ''
        },
    },
    {
        id: 'snt_faq',
        name: 'Sintéticos: FAQ',
        icon: 'quiz',
        category: 'content',
        description: '8 preguntas frecuentes oficiales (Contenido Fijo)',
        sourceTemplate: 1,
        defaultContent: {},
    },
    {
        id: 'snt_cta',
        name: 'Sintéticos: CTA Final',
        icon: 'ads_click',
        category: 'cta',
        description: 'Cierre motivacional general',
        sourceTemplate: 1,
        defaultContent: {
            ctaText: 'Abrir cuenta ahora',
            ctaSecondary: 'Ver gráficos en vivo'
        },
    },
    {
        id: 'snt_footer',
        name: 'Sintéticos: Footer',
        icon: 'bottom_panel_open',
        category: 'layout',
        description: 'Footer corporativo con atribución IB y datos legales fijos',
        sourceTemplate: 1,
        defaultContent: {
            ibFooterName: 'Presentado por IB Oficial',
            ibContactInfo: 'contacto@tucomunidad.com'
        },
    },
    // ─── BLUEPRINT 2: PROPFIRM ──────────────────────────
    {
        id: 'prop_hero',
        name: 'PropFirm: Hero',
        icon: 'stadium',
        category: 'hero',
        description: 'Hero oficial de cuentas fondeadas',
        sourceTemplate: 1,
        defaultContent: {
            heroSub: 'Alcanza la libertad financiera operando con nuestro capital.',
            ctaBtn: 'Comprar Challenge'
        },
    },
    {
        id: 'prop_about',
        name: 'PropFirm: Definición',
        icon: 'help_center',
        category: 'content',
        description: '¿Qué es PropTrading? Explicación fija',
        sourceTemplate: 1,
        defaultContent: {
            aboutTitle: '¿Cómo funciona nuestro sistema?'
        },
    },
    {
        id: 'prop_matrix',
        name: 'PropFirm: Programas',
        icon: 'table_view',
        category: 'content',
        description: 'Tablas comparativas Forex vs Sintéticos',
        sourceTemplate: 1,
        defaultContent: {
            matrixTitle: 'Nuestros Challenge'
        },
    },
    {
        id: 'prop_workflow',
        name: 'PropFirm: Proceso',
        icon: 'route',
        category: 'content',
        description: '4 pasos del flujo PropTrading',
        sourceTemplate: 1,
        defaultContent: {
            workflowTitle: 'Camino al Fondeo'
        },
    },
    {
        id: 'prop_rules',
        name: 'PropFirm: Reglas Clave',
        icon: 'gavel',
        category: 'content',
        description: '8 reglas operativas oficiales',
        sourceTemplate: 1,
        defaultContent: {
            rulesTitle: 'Reglas de Trading Justas'
        },
    },
    {
        id: 'prop_benefits',
        name: 'PropFirm: Beneficios',
        icon: 'verified',
        category: 'content',
        description: 'Certificación y ventajas del trader',
        sourceTemplate: 1,
        defaultContent: {
            benefitsTitle: 'Beneficios Exclusivos'
        },
    },
    {
        id: 'prop_community',
        name: 'PropFirm: Comunidad',
        icon: 'forum',
        category: 'content',
        description: 'Sección editable del IB',
        sourceTemplate: 1,
        defaultContent: {
            communityTitle: 'Únete a nuestra academia de fondeados',
            communityDesc: 'Recibe acompañamiento diario para pasar tu prueba de fondeo con éxito.',
            telegramBtn: 'Unirse al Grupo'
        },
    },
    {
        id: 'prop_faq',
        name: 'PropFirm: FAQ',
        icon: 'live_help',
        category: 'content',
        description: '8 FAQs oficiales de PropTrading',
        sourceTemplate: 1,
        defaultContent: {
            faqTitle: 'Dudas Frecuentes'
        },
    },
    {
        id: 'prop_cta',
        name: 'PropFirm: CTA Final',
        icon: 'touch_app',
        category: 'cta',
        description: 'Doble CTA con advertencia legal',
        sourceTemplate: 1,
        defaultContent: {
            ctaTitle: 'Elige tu Plan y Comienza Hoy',
            ctaBtn: 'Ver Tablas de Precios'
        },
    },
    {
        id: 'prop_footer',
        name: 'PropFirm: Footer',
        icon: 'dock',
        category: 'layout',
        description: 'Pie corporativo para cuentas fondeadas',
        sourceTemplate: 1,
        defaultContent: {
            footerText: 'Operar cuentas de fondeo simuladas conlleva cumplimiento de reglas estrictas.'
        },
    },
    // ─── BLUEPRINT 3: MAM & COPY TRADING ─────────────────
    {
        id: 'mc_hero',
        name: 'MAM/Copy: Hero Dual',
        icon: 'dual_screen',
        category: 'hero',
        description: 'Hero con enfoque dual en MAM y Copy Trading, incluye badges de producto.',
        sourceTemplate: 3,
        defaultContent: {
            title: 'Gestiona o invierte capital de forma profesional, automatizada y transparente.',
            subtitle: 'Accede a las Cuentas MAM y al Copy Trading de Bridge Markets. Dos soluciones. Un mismo ecosistema profesional.',
            cta1: 'Quiero una cuenta MAM',
            cta2: 'Quiero hacer Copy Trading'
        },
    },
    {
        id: 'mc_intro',
        name: 'MAM/Copy: Introducción',
        icon: 'article',
        category: 'content',
        description: 'Sección puente que contextualiza ambos productos.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_mam_block',
        name: 'MAM/Copy: Bloque MAM',
        icon: 'account_balance',
        category: 'content',
        description: 'Sección completa del producto MAM: Definición, Equity/Cash, LPOA y Pasos.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_copy_block',
        name: 'MAM/Copy: Bloque Copy',
        icon: 'content_copy',
        category: 'content',
        description: 'Sección completa del producto Copy Trading: Definición y ventajas.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_comparison',
        name: 'MAM/Copy: Comparativa',
        icon: 'compare_arrows',
        category: 'content',
        description: 'Tabla comparativa técnica entre MAM y Copy Trading.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_benefits',
        name: 'MAM/Copy: Beneficios',
        icon: 'done_all',
        category: 'content',
        description: 'Grid de beneficios generales del sistema Bridge Markets.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_dual_steps',
        name: 'MAM/Copy: Pasos Inicio',
        icon: 'reorder',
        category: 'content',
        description: 'Doble track de pasos para Gestores e Inversionistas.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_community',
        name: 'MAM/Copy: Comunidad IB',
        icon: 'groups',
        category: 'content',
        description: 'Sección personalizable del IB para su marca y comunidad.',
        sourceTemplate: 3,
        defaultContent: {
            communityName: 'Trading Profesional',
            welcomeMessage: 'Somos tu principal aliado estratégico. Únete y accede a herramientas únicas para potenciar tus resultados.',
            btnText: 'Únete a mi comunidad',
            bannerUrl: ''
        },
    },
    {
        id: 'mc_faq',
        name: 'MAM/Copy: FAQ Dual',
        icon: 'quiz',
        category: 'content',
        description: 'Preguntas frecuentes divididas por producto.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_final_cta',
        name: 'MAM/Copy: CTA Final',
        icon: 'ads_click',
        category: 'cta',
        description: 'Cierre con llamado a la acción dual y disclaimer.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'mc_footer',
        name: 'MAM/Copy: Footer',
        icon: 'bottom_panel_open',
        category: 'layout',
        description: 'Footer corporativo con atribución al IB.',
        sourceTemplate: 3,
        defaultContent: {},
    },
    {
        id: 'lx12_hero',
        name: 'Pro Leverage: Hero',
        icon: 'bolt',
        category: 'hero',
        description: 'Hero premium para cuentas apalancadas x12 sin evaluación.',
        sourceTemplate: 4,
        defaultContent: {
            title: 'Opera con capital real. Sin evaluaciones. Sin esperas.',
            subtitle: 'Multiplica tu capital hasta x12 y opera directamente en mercados CFDs con una cuenta real financiada por Bridge Markets.',
            ctaText: 'Quiero mi cuenta apalancada'
        },
    },
    {
        id: 'lx12_intro',
        name: 'Pro Leverage: Definición',
        icon: 'info',
        category: 'content',
        description: 'Sección educativa sobre qué es la cuenta Pro Leverage X12.',
        sourceTemplate: 4,
        defaultContent: {},
    },
    {
        id: 'lx12_table_compare',
        name: 'Pro Leverage: vs PropFirm',
        icon: 'compare',
        category: 'content',
        description: 'Tabla comparativa oficial entre Pro Leverage X12 y PropFirm.',
        sourceTemplate: 4,
        defaultContent: {},
    },
    {
        id: 'lx12_pricing',
        name: 'Pro Leverage: Precios',
        icon: 'payments',
        category: 'content',
        description: 'Selector de tamaños de cuenta y precios oficiales.',
        sourceTemplate: 4,
        defaultContent: {
            ctaText: 'Comprar ahora'
        },
    },
    {
        id: 'lx12_example',
        name: 'Pro Leverage: Ejemplo x12',
        icon: 'calculate',
        category: 'content',
        description: 'Ejemplo numérico visual de apalancamiento.',
        sourceTemplate: 4,
        defaultContent: {},
    },
    {
        id: 'lx12_rules',
        name: 'Pro Leverage: Reglas',
        icon: 'gavel',
        category: 'content',
        description: 'Acordeón de reglas operativas (Pérdida 10%, Scalping, etc.).',
        sourceTemplate: 4,
        defaultContent: {},
    },
    {
        id: 'lx12_withdrawals',
        name: 'Pro Leverage: Retiros',
        icon: 'account_balance_wallet',
        category: 'content',
        description: 'Ventanas de retiro (Día 3 y Día 45) y liquidación.',
        sourceTemplate: 4,
        defaultContent: {},
    },
    {
        id: 'lx12_benefits',
        name: 'Pro Leverage: Beneficios',
        icon: 'stars',
        category: 'content',
        description: '6 tarjetas de beneficios clave.',
        sourceTemplate: 4,
        defaultContent: {},
    },
    {
        id: 'lx12_community',
        name: 'Pro Leverage: Comunidad IB',
        icon: 'groups',
        category: 'content',
        description: 'Sección editable con banner y contacto del IB.',
        sourceTemplate: 4,
        defaultContent: {
            communityName: 'Comunidad Pro Traders',
            welcomeMessage: 'Impulsa tu carrera al siguiente nivel con el respaldo de capital real y soporte continuo.',
            telegramLink: '',
            whatsappNumber: ''
        },
    },
    {
        id: 'lx12_faq',
        name: 'Pro Leverage: FAQ',
        icon: 'live_help',
        category: 'content',
        description: 'Preguntas frecuentes sobre Pro Leverage X12.',
        sourceTemplate: 4,
        defaultContent: {},
    },
    {
        id: 'lx12_final_cta',
        name: 'Pro Leverage: CTA Final',
        icon: 'ads_click',
        category: 'cta',
        description: 'Cierre de la landing con aviso de riesgo.',
        sourceTemplate: 4,
        defaultContent: {
            ctaText: 'Empezar ahora'
        },
    },
    {
        id: 'inst_hero',
        name: 'Institucional: Hero',
        icon: 'home',
        category: 'hero',
        description: 'Hero corporativo con badges de confianza y enfoque en ecosistema global.',
        sourceTemplate: 5,
        defaultContent: {
            title: 'Tu ecosistema financiero completo.',
            highlight: 'Opera, invierte y crece.',
            subtitle: 'Desde Forex y CFDs hasta índices sintéticos exclusivos. Cuentas para traders, inversores y gestores. Un solo broker. Todo lo que necesitas.',
            ibPhrase: 'Bienvenidos al futuro del trading institucional con Bridge Markets.',
            cta1: 'Abrir mi cuenta',
            cta2: 'Ver todos los productos'
        },
    },
    {
        id: 'inst_about',
        name: 'Institucional: Quiénes Somos',
        icon: 'corporate_fare',
        category: 'content',
        description: 'Sección breve con historia, misión y datos registrales oficiales.',
        sourceTemplate: 5,
        defaultContent: {},
    },
    {
        id: 'inst_why',
        name: 'Institucional: Por Qué BM',
        icon: 'ads_click',
        category: 'content',
        description: 'Grid de 9 razones clave para elegir Bridge Markets.',
        sourceTemplate: 5,
        defaultContent: {},
    },
    {
        id: 'inst_ecosystem',
        name: 'Institucional: Ecosistema',
        icon: 'hub',
        category: 'content',
        description: 'Grid de productos con descripción y enlaces a landings específicas.',
        sourceTemplate: 5,
        defaultContent: {},
    },
    {
        id: 'inst_selector',
        name: 'Institucional: Perfil',
        icon: 'person_search',
        category: 'content',
        description: 'Bifurcación interactiva: ¿Eres Trader o Inversor?',
        sourceTemplate: 5,
        defaultContent: {
            ctaTrader: 'Empezar como Trader',
            ctaInvestor: 'Empezar como Inversor'
        },
    },
    {
        id: 'inst_partners',
        name: 'Institucional: Socios IB',
        icon: 'partnership',
        category: 'content',
        description: 'Beneficios del programa de Introducing Brokers.',
        sourceTemplate: 5,
        defaultContent: {
            ctaText: 'Quiero ser IB'
        },
    },
    {
        id: 'inst_tech',
        name: 'Institucional: Tecnología',
        icon: 'terminal',
        category: 'content',
        description: 'Plataformas MT5, Charts propios y Portal de Cliente.',
        sourceTemplate: 5,
        defaultContent: {},
    },
    {
        id: 'inst_workflow',
        name: 'Institucional: Cómo Empezar',
        icon: 'format_list_numbered',
        category: 'content',
        description: 'Stepper de 7 pasos universales para onboarding.',
        sourceTemplate: 5,
        defaultContent: {},
    },
    {
        id: 'inst_community',
        name: 'Institucional: Comunidad IB',
        icon: 'groups',
        category: 'content',
        description: 'Sección flexible para conectar la marca del IB con Bridge Markets.',
        sourceTemplate: 5,
        defaultContent: {
            communityName: 'Trading Global Hub',
            welcomeMessage: 'Nuestra comunidad está diseñada para potenciar tu crecimiento con herramientas y soporte directo para alcanzar la rentabilidad.',
            telegramLink: '',
            whatsappNumber: ''
        },
    },
    {
        id: 'inst_faq',
        name: 'Institucional: FAQ',
        icon: 'quiz',
        category: 'content',
        description: '10 preguntas comunes sobre el broker y su operativa.',
        sourceTemplate: 5,
        defaultContent: {},
    },
    {
        id: 'inst_final_cta',
        name: 'Institucional: CTA Final',
        icon: 'stars',
        category: 'cta',
        description: 'Cierre institucional con múltiples puntos de entrada.',
        sourceTemplate: 5,
        defaultContent: {
            ctaMain: 'Abrir cuenta ahora',
            ctaSecondary: 'Explorar productos',
            ctaIB: 'Quiero ser IB'
        },
    },
    {
        id: 'inst_footer',
        name: 'Institucional: Footer',
        icon: 'bottom_panel_open',
        category: 'layout',
        description: 'Footer completo con datos legales y atribución IB.',
        sourceTemplate: 5,
        defaultContent: {
            ibName: 'Presentado por Partner Oficial'
        },
    },
    {
        id: 'snu_hero',
        name: 'Universo: Hero',
        icon: 'diamond',
        category: 'hero',
        description: 'Hero con estética de galaxia y badge de exclusividad BM.',
        sourceTemplate: 6,
        defaultContent: {
            title: 'Opera todos los índices sintéticos del mercado. Un solo broker. Una sola cuenta.',
            subtitle: 'Bridge Markets es el único broker que conecta en una sola cuenta los índices de Deriv, los de Weltrade y sus propios índices exclusivos. Más de 100 instrumentos. Disponibles 24/7.',
            ibPhrase: 'Bienvenidos al ecosistema de trading más potente del mercado global.',
            cta: 'Abrir mi cuenta ahora'
        },
    },
    {
        id: 'snu_metrics',
        name: 'Universo: Métricas',
        icon: 'query_stats',
        category: 'content',
        description: 'Tarjetas de impacto con contadores de instrumentos y universos.',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_universes_intro',
        name: 'Universo: Los 3 Ecosistemas',
        icon: 'filter_3',
        category: 'content',
        description: 'Introducción visual a los 3 universos (BM, Deriv, Weltrade).',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_u1_bm',
        name: 'Universo: 1. Índices Propios',
        icon: 'token',
        category: 'content',
        description: 'Detalle de familias Fortune, Vortex, BullX, BearX y FomoX.',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_u2_deriv',
        name: 'Universo: 2. Mercados Deriv',
        icon: 'layers',
        category: 'content',
        description: 'Tabla de equivalencias SOURCE DERIV -> SYMBOL BRIDGE.',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_u3_welt',
        name: 'Universo: 3. Mercados Weltrade',
        icon: 'dynamic_feed',
        category: 'content',
        description: 'Detalle de familias VolFX, SpikeFX, FlipX y StepRise/Drop.',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_why',
        name: 'Universo: Por Qué BM',
        icon: 'verified',
        category: 'content',
        description: '6 argumentos competitivos de superioridad técnica.',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_workflow',
        name: 'Universo: Cómo Empezar',
        icon: 'ads_click',
        category: 'content',
        description: 'Proceso de 7 pasos para activar la operativa sintética.',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_community',
        name: 'Universo: Comunidad IB',
        icon: 'forum',
        category: 'content',
        description: 'Sección flexible para el mensaje personal del IB.',
        sourceTemplate: 6,
        defaultContent: {
            communityName: 'Synthetic Academy',
            welcomeMessage: 'Nuestra misión es educarte para que domines el algoritmo y generes consistencia real en el mercado sintético.'
        },
    },
    {
        id: 'snu_faq',
        name: 'Universo: FAQ',
        icon: 'help_center',
        category: 'content',
        description: 'Preguntas técnicas sobre latencia, robots y 24/7.',
        sourceTemplate: 6,
        defaultContent: {},
    },
    {
        id: 'snu_cta',
        name: 'Universo: CTA Final',
        icon: 'rocket_launch',
        category: 'cta',
        description: 'Cierre con frase de remate y botones de acción.',
        sourceTemplate: 6,
        defaultContent: {
            title: 'Deriv, Weltrade y propios BM. Todo en Bridge Markets.',
            subtitle: 'Más de 100 instrumentos. Tres ecosistemas. Una sola cuenta. Disponible 24/7.',
            ctaPrimary: 'Abrir mi cuenta ahora',
            ctaSecondary: 'Ver gráficos en vivo'
        },
    },
    {
        id: 'snu_footer',
        name: 'Universo: Footer',
        icon: 'subtitles',
        category: 'layout',
        description: 'Footer institucional con enlaces a charts y documentos.',
        sourceTemplate: 6,
        defaultContent: {
            ibName: 'Presentado por IB Sintéticos'
        },
    },
    // ─── BLUEPRINT 7: PROPFIRM SINTÉTICOS PREMIUM ──────────
    {
        id: 'ps_hero',
        name: 'PS: Hero Cyber Purple',
        icon: 'stadium',
        category: 'hero',
        description: 'Hero ultra-premium con estética púrpura y blur cards.',
        sourceTemplate: 7,
        defaultContent: {
            title: 'POTENCIALIZA',
            highlight: 'TU TRADING',
            subtitle: 'Opera con capital institucional en el mercado más dinámico del mundo.',
            ctaText: 'Empieza Ahora',
            badgeText: 'EL MEJOR CHALLENGE DEL MERCADO'
        },
    },
    {
        id: 'ps_banner',
        name: 'PS: Social Proof Banner',
        icon: 'view_list',
        category: 'content',
        description: 'Banner flotante con estadísticas y beneficios flash.',
        sourceTemplate: 7,
        defaultContent: {
            items: ['Ejecución Instantánea', 'Spread 0.0', 'Soporte 24/7', 'Retiros cada 14 días']
        },
    },
    {
        id: 'ps_features',
        name: 'PS: Grid de Ventajas',
        icon: 'grid_view',
        category: 'content',
        description: 'Grid de 3 columnas con iconos neón y borde de cristal.',
        sourceTemplate: 7,
        defaultContent: {
            title: '¿Por qué elegir nuestro reto?',
            features: [
                { icon: 'bolt', title: 'Velocidad', desc: 'Conectividad directa con los servidores de baja latencia.' },
                { icon: 'security', title: 'Seguridad', desc: 'Fondos segregados y protección contra saldo negativo.' },
                { icon: 'analytics', title: 'Analítica', desc: 'Dashboard avanzado para monitorear tu operativa.' }
            ]
        },
    },
    {
        id: 'ps_matrix',
        name: 'PS: Tabla de Planes',
        icon: 'table_chart',
        category: 'content',
        description: 'Tabla de retos oficiales (2 Fases) con precios.',
        sourceTemplate: 7,
        defaultContent: {
            title: 'REGLAS BM 2 FASES',
            plans: [
                { size: '$5,000', price: '$49' },
                { size: '$10,000', price: '$89' },
                { size: '$25,000', price: '$189' },
                { size: '$50,000', price: '$329' },
                { size: '$100,000', price: '$549' }
            ]
        },
    },
    {
        id: 'ps_calculator',
        name: 'PS: Calculadora de Ganancias',
        icon: 'calculate',
        category: 'content',
        description: 'Calculadora interactiva de profit basada en el target del 4%.',
        sourceTemplate: 7,
        defaultContent: {
            title: 'Calcula tus ganancias',
            note: 'Basado en un target conservador de 4% mensual.'
        },
    },
    {
        id: 'ps_rules',
        name: 'PS: Reglas y Cumplimiento',
        icon: 'gavel',
        category: 'content',
        description: 'Sección de reglas operativas detalladas.',
        sourceTemplate: 7,
        defaultContent: {
            title: 'Protocolos Operativos',
            rules: [
                { title: 'Drawdown Diario', value: '5%' },
                { title: 'Drawdown Total', value: '10%' },
                { title: 'Objetivo Fase 1', value: '8%' },
                { title: 'Objetivo Fase 2', value: '5%' }
            ]
        },
    },
    {
        id: 'ps_contact',
        name: 'PS: Contacto CTA',
        icon: 'contact_support',
        category: 'cta',
        description: 'Sección final de contacto con formulario y título gigante.',
        sourceTemplate: 7,
        defaultContent: {
            title: 'CONTÁCTANOS',
            subtitle: '¿Tienes dudas? Nuestro equipo está listo para ayudarte.'
        },
    },
    {
        id: 'ps_footer',
        name: 'PS: Footer Especializado',
        icon: 'bottom_panel_open',
        category: 'layout',
        description: 'Footer oscuro con logos y atribución legal.',
        sourceTemplate: 7,
        defaultContent: {
            disclaimer: 'El trading conlleva un riesgo significativo.'
        },
    },
];


export const SECTION_CATEGORIES: Record<string, { label: string; icon: string }> = {
    hero: { label: 'Heroes', icon: 'view_carousel' },
    content: { label: 'Contenido', icon: 'dashboard' },
    social_proof: { label: 'Validación', icon: 'verified_user' },
    cta: { label: 'Llamados a la Acción', icon: 'ads_click' },
    layout: { label: 'Estructura', icon: 'view_agenda' }
};
